version: "3"

services:

    asyncsync:
        image: "asyncsync"
        build: 
          context: .
          dockerfile: 'AspNetCore.AsyncRequests/Dockerfile'
        expose:
            - "80"
        environment: 
            ASPNETCORE_ENVIRONMENT: Development
    
    proxy:
        container_name: asyncsync_proxy
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - '5000:80'
        depends_on:
            - 'asyncsync'
 